name: 4-layer-sweep-no-mup
method: grid
metric:
  goal: minimize
  name: loss
parameters:
  file_type:
    value: auto
  col_name:
    value: contents
  tokenizer_path:
    value: /datasets/tokenizers/llama3
  weights:
    value: 1
  vocab_size:
    value: 128256
  bos_token:
    value: null
  eos_token:
    value: 128000
  use_torch_compile:
    value: False
  data_path:
    value: /datasets/dolma_v1_7
  datasets:
    value: dataset=cc_en_head
  tracker:
    value: wandb
  n_layer:
    value: 4
  head_dim:
    value: 128
  d_model:
    values:
      - 256
      - 512
      - 1024
      - 2048
      - 4096
      - 8192
  optim:
    value: adamw
  mup_base_d_model:
    value: 256
  seq_length:
    value: 512
  batch_size:
    value: 8
  acc_steps:
    value: 1
  world_size:
    value: 8
  num_steps:
    value: 8192
  report_interval:
    value: 64
  mup:
    value: false
  # LRs: log-spaced
  learning_rate:
    values:
      - 0.1
      - 0.046415888336127795
      - 0.021544346900318832
      - 0.01
      - 0.004641588833612777
      - 0.0021544346900318843
      - 0.001
      - 0.00046415888336127773
      - 0.00021544346900318845
      - 0.0001
      - 4.641588833612782e-05
      - 2.1544346900318823e-05
      - 1e-05
