name: 4-layer-sweep-sgd
method: grid
metric:
  goal: minimize
  name: loss
parameters:
  file_type:
    value: auto
  col_name:
    value: contents
  tokenizer_path:
    value: /datasets/tokenizers/llama3
  weights:
    value: 1
  vocab_size:
    value: 128256
  bos_token:
    value: null
  eos_token:
    value: 128000
  use_torch_compile:
    value: False
  data_path:
    value: /datasets/dolma_v1_7
  datasets:
    value: dataset=cc_en_head
  tracker:
    value: wandb
  n_layer:
    value: 4
  head_dim:
    value: 128
  d_model:
    values:
      - 256
      - 512
      - 1024
      - 2048
      - 4096
      - 8196
  optim:
    value: sgd
  mup_base_d_model:
    value: 256
  seq_length:
    value: 512
  batch_size:
    value: 4
  acc_steps:
    value: 16
  num_steps:
    value: 2048
  report_interval:
    value: 64
  mup:
    values:
    - true
    - false
  mup_simple_scaling_impl:
    value: false
  # LRs: log-spaced
  learning_rate:
    values:
    - 100.0
    - 56.23413251903491
    - 31.622776601683793
    - 17.78279410038923
    - 10.0
    - 5.623413251903491
    - 3.1622776601683795
    - 1.7782794100389228
    - 1.0
    - 0.5623413251903491
    - 0.31622776601683794
    - 0.1778279410038923
    - 0.1
    - 0.05623413251903491
    - 0.03162277660168379
    - 0.01778279410038923
    - 0.01
